### ISSUE TITLE
Blog post - documenting things & Posit - Sept 27?

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#285]
I wrote up what I would relay to Stef, Erin, Amy Steiker (as 3 people in mind for writing this debrief) - now in a PR (https://github.com/Openscapes/website-new/pull/58) for Stef. We can discuss blog post timelines this week.

**Comment by stefaniebutland** [comment]
[published](https://openscapes.org/blog/2023-09-27-documenting-things-posit-conf/) and [tooted](https://fosstodon.org/@openscapes/111139048117271821) 

@jules32 would you rather have selflie (you Hadley, Hannah, et al) for feature image instead of screenshot? Suits vibe better than a screenshot....or I can save time by not changing it ;-)

**Comment by jules32** [comment]
Screenshot looks good, thank you!!
