### ISSUE TITLE
Reflections Program - Apr 29 - May 17

### ISSUE THREAD

**Issue by jules32** [Openscapes/how_we_work#337]
Ileana, Julie, Stef huddling on Thursday to review plan & prep for next week.

Mondays: send email with prompts. Apr 29: also send calendar invites for optional huddles (feedback from lasttime).

**Comment by stefaniebutland** [comment]
## Roles

### Hosts, read prompts, facilitate discussions
Ileana & Julie

### Tech support
Stef
- Tuesday - welcome email, google folder, calendar invites 
  - email text in Visioning doc, [Program details in booklet](https://openscapes.github.io/booklet/#program-details)
- During and After Calls
  - admit folks to Zoom
  - record & Clip videos so only intros + prompts & put on YouTube [Reflections Playlist](https://www.youtube.com/playlist?list=PLVVMU2rjWU7dtsQl5mLtn57qo-EwlgBU3)
  - play songs from Spotify Openscapes Reflections (how-to in Approach Guide: [Sharing audio in Zoom](https://openscapes.github.io/approach-guide/approach/tooling.html#zoom))
  - in 2023, we tweet/tooted after Huddle; text in Visioning doc


## Notes

- [ ] YouTube Recording 1 hidden due to song license issue I think - Stef check on this issue; address for this year

-

**Comment by jules32** [comment]
Scheduled Tuesday's email for Week 2!

**Comment by stefaniebutland** [comment]
Huddle 2 recording & slides shortcut now in OpenscapesReflections [ 2024-spring ] folder

**Comment by jules32** [comment]
Just huddled with Ileana and all set for tomorrow! We also reviewed the survey to include in the thank you email (and decided not to spend time on survey live together, the same from last year).

**Comment by jules32** [comment]
@stefaniebutland, Ileana and I reviewed the Thank you email and think it's good to go - could you please have a final look and send participants today or tomorrow? And we'll follow up with a blog post later in the summer

**Comment by stefaniebutland** [comment]
I've tagged you on a question in the doc re: email.

2024 recordings now on YouTube in Reflections playlist. 2023 recordings set to "unlisted" - only people who know the link to the video can view it

**Comment by stefaniebutland** [comment]
Closing after successful year 2 of Reflections. Ileana & Julie will draft a blog post later
